[package]
name = "lokichain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bech32 = "0.11"
base64 = "0.22"
rand = "0.8"
chrono = "0.4.39"